inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.mi_vista, name='inicio'),
    path('lista-de-gastos/', views.lista_de_gastos, name='lista_de_gastos'),
    path('gastos-realizados/', views.gastos_realizados, name='gastos_realizados'),
]

proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('admin/', admin.site.urls),
]

inicio/models.py
from django.db import models



class Gasto(models.Model):
    Tipo = models.CharField(max_length=20)
    Articulo =  models.CharField(max_length=20)
    Cantidad = models.IntegerField()
    Precio = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    
    def __str__(self):
        return f'{self.Tipo} {self.Articulo} {self.Cantidad} {self.Precio}'

inicio/forms.py
from django import forms




class GastosFormulario(forms.Form):
    Tipo = forms.CharField(max_length=20)
    Articulo =  forms.CharField(max_length=20)
    Cantidad = forms.IntegerField()
    Precio = forms.DecimalField(max_digits=10, decimal_places=2)
  
    

    
class BuscarGastos(forms.Form):
    Tipo = forms.CharField(max_length=20, required=False)
    Articulo =  forms.CharField(max_length=20)
    Cantidad = forms.IntegerField()
    Precio = forms.DecimalField(max_digits=10, decimal_places=2, required=False)
  
    
    
    

inicio/views.py
from django.shortcuts import render, redirect
from inicio.forms import BuscarGastos, GastosFormulario
from inicio.models import Gasto

def mi_vista(request):
    return render(request, 'inicio/index.html')

def gastos_realizados(request):
    if request.method == "POST":
        formulario = GastosFormulario(request.POST)
        if formulario.is_valid():
            datos_correctos = formulario.cleaned_data
            gastos = Gasto(
                Tipo=datos_correctos['Tipo'],
                Articulo=datos_correctos['Articulo'],
                Cantidad=datos_correctos['Cantidad'],
                Precio=datos_correctos['Precio'],
            )
            gastos.save()
            return redirect('inicio:lista_de_gastos')
    formulario = GastosFormulario()
    return render(request, 'inicio/gastos_realizados.html', {'formulario': formulario})

def lista_de_gastos(request):
    tipo_a_buscar = request.GET.get('Tipo', None)
    articulo_a_buscar = request.GET.get('Articulo', None)
    cantidad_a_buscar = request.GET.get('Cantidad', None)
    precio_a_buscar = request.GET.get('Precio', None)
    if tipo_a_buscar:
        gastos = Gasto.objects.filter(Tipo__icontains=tipo_a_buscar)
    elif articulo_a_buscar:
        gastos = Gasto.objects.filter(Articulo__icontains=articulo_a_buscar)
    elif cantidad_a_buscar:
        gastos = Gasto.objects.filter(Cantidad=cantidad_a_buscar)
    elif precio_a_buscar:
        gastos = Gasto.objects.filter(Precio=precio_a_buscar)
    else:
        gastos = Gasto.objects.all()
    formulario_busqueda = BuscarGastos()
    return render(request, 'inicio/lista_de_gastos.html', {'gastos': gastos, 'formulario': formulario_busqueda})

inicio/templates/inicio/gastos_realizados.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Gastos realizados</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Gastos Realizados</h1>
{% endblock h1_header %}


{% block contenido %}
<form action={% url 'inicio:gastos_realizados' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    
    <button>Crear</button>
</form>
{% endblock contenido %}

inicio/templates/inicio/index.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Bienvenidos a NUESTRA agenda de Gastos </h1>
{% endblock h1_header %}

inicio/templates/inicio/lista_de_gastos.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Gastos Totales</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Listado de Gastos</h1>
{% endblock h1_header %}


{% block contenido %}
<p>
    <form action={% url 'inicio:lista_de_gastos' %}>
        {{formulario}}
        <button>Buscar</button>
    </form>
</p>

{% if gastos %}
    {% for gasto in gastos %}
    <li>
        tipo: {{gasto.Tipo}} - articulo: {{gasto.Articulo}} - cantidad: {{gasto.Cantidad}} - precio: {{gasto.Precio}}
    </li>
    {% endfor %}

{% else %}
    <h2>No hay datos sobre gastos por el momento.</h2>
{% endif %}
{% endblock contenido %}

templates/genericos/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'inicio/css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                
                <a class="navbar-brand" href={% url 'inicio:gastos_realizados' %}>Gastos</a>
            
                <a class="navbar-brand" href={% url 'inicio:lista_de_gastos' %}>Lista de gastos</a>
                
            </div>
        </nav>
        <!-- Masthead-->
        {% block header %}
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            {% block h1_header %}
                            <h1 class="mb-5">Estas usando el h1 base</h1>
                            {% endblock h1_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'inicio/js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>